import { Affectation, Materiel } from "./materiel-model";

export const CATEGORIEMATERIEL: any[] = [
  { value: "logistique" },
  { value: "technique" }
]

export const TYPEDEMATERIEL: any[] = [
  { value: "logiciel" },
  { value: "mobilier" },
  { value: "materiel de bureau" },
  { value: "informatique" }
]

export const TYPEDEMAINTENANCE: any[] = [
  { value: "bimensuel" },
  { value: "trimensuel" },
  { value: "semestriel" },
  { value: "annuel" },
  { value: "occasionnel" }
]

export const ETAT: any[] = [
  { value: "actif" },
  { value: "reforme" },
  { value: "alerte" },
  { value: "signale" }
]

export const AFFECTATIONS: Affectation[] = [
  {
    id: 1,
    dateFiche: "28/12/2022",
    identFiche: "Lorem ispum dolor",
    refFiche: "Lorem ispum dolor",
    identMateriel: "Lorem ispum dolor",
    adresseMacMateriel: "Lorem ispum dolor",
    refInterneMateriel: "Lorem ispum dolor",
    destinataire: "Libasse YADE",
    dateDotation: "28/12/2022",
    objetDotation: "Lorem ispum dolor",
    datePrevueRetour: "28/01/2022",
    localisationGeo: "Lorem ispum dolor",
    avisDestinataire: "Lorem ispum dolor",
    designationMateriel: "Lorem ispum dolor",
    refComMateriel: "Lorem ispum dolor",
    dateRetour: "28/01/2022",
    avisServiceSupportAssistance: "Lorem ispum dolor",
    typeAvis:"default",
    newAffectation:true,
    etat:"Actif"
  },
  {
    id: 2,
    dateFiche: "28/12/2022",
    identFiche: "Lorem ispum dolor",
    refFiche: "Lorem ispum dolor",
    identMateriel: "Lorem ispum dolor",
    adresseMacMateriel: "Lorem ispum dolor",
    refInterneMateriel: "Lorem ispum dolor",
    destinataire: "Adama GUEYE",
    dateDotation: "28/12/2022",
    objetDotation: "Lorem ispum dolor",
    datePrevueRetour: "28/01/2022",
    localisationGeo: "Lorem ispum dolor",
    avisDestinataire: "Lorem ispum dolor",
    designationMateriel: "Lorem ispum dolor",
    refComMateriel: "Lorem ispum dolor",
    dateRetour: "28/01/2022",
    avisServiceSupportAssistance: "Lorem ispum dolor",
    typeAvis:"accepter",
    newAffectation:false,
    etat:"Actif"
  },
  {
    id: 3,
    dateFiche: "28/12/2022",
    identFiche: "Lorem ispum dolor",
    refFiche: "Lorem ispum dolor",
    identMateriel: "Lorem ispum dolor",
    adresseMacMateriel: "Lorem ispum dolor",
    refInterneMateriel: "Lorem ispum dolor",
    destinataire: "Lamine DIEME",
    dateDotation: "28/12/2022",
    objetDotation: "Lorem ispum dolor",
    datePrevueRetour: "28/01/2022",
    localisationGeo: "Lorem ispum dolor",
    avisDestinataire: "Lorem ispum dolor",
    designationMateriel: "Lorem ispum dolor",
    refComMateriel: "Lorem ispum dolor",
    dateRetour: "28/01/2022",
    avisServiceSupportAssistance: "Lorem ispum dolor",
    typeAvis:"accepter",
    newAffectation:false,
    etat:"Alerte"
  },
  {
    id: 4,
    dateFiche: "28/12/2022",
    identFiche: "Lorem ispum dolor",
    refFiche: "Lorem ispum dolor",
    identMateriel: "Lorem ispum dolor",
    adresseMacMateriel: "Lorem ispum dolor",
    refInterneMateriel: "Lorem ispum dolor",
    destinataire: "Alioune Badara",
    dateDotation: "28/12/2022",
    objetDotation: "Lorem ispum dolor",
    datePrevueRetour: "28/01/2022",
    localisationGeo: "Lorem ispum dolor",
    avisDestinataire: "Lorem ispum dolor",
    designationMateriel: "Lorem ispum dolor",
    refComMateriel: "Lorem ispum dolor",
    dateRetour: "28/01/2022",
    avisServiceSupportAssistance: "Lorem ispum dolor",
    typeAvis:"accepter",
    newAffectation:false,
    etat:"Alerte"
  },
  {
    id: 5,
    dateFiche: "28/12/2022",
    identFiche: "Lorem ispum dolor",
    refFiche: "Ibrahima FALL",
    identMateriel: "Lorem ispum dolor",
    adresseMacMateriel: "Lorem ispum dolor",
    refInterneMateriel: "Lorem ispum dolor",
    destinataire: "Lorem ispum dolor",
    dateDotation: "28/12/2022",
    objetDotation: "Lorem ispum dolor",
    datePrevueRetour: "28/01/2022",
    localisationGeo: "Lorem ispum dolor",
    avisDestinataire: "Lorem ispum dolor",
    designationMateriel: "Lorem ispum dolor",
    refComMateriel: "Lorem ispum dolor",
    dateRetour: "28/01/2022",
    avisServiceSupportAssistance: "Lorem ispum dolor",
    typeAvis:"accepter",
    newAffectation:false,
    etat:"Reformé"
  },
  {
    id: 6,
    dateFiche: "28/12/2022",
    identFiche: "Lorem ispum dolor",
    refFiche: "Ibrahima FALL",
    identMateriel: "Lorem ispum dolor",
    adresseMacMateriel: "Lorem ispum dolor",
    refInterneMateriel: "Lorem ispum dolor",
    destinataire: "Lorem ispum dolor",
    dateDotation: "28/12/2022",
    objetDotation: "Lorem ispum dolor",
    datePrevueRetour: "28/01/2022",
    localisationGeo: "Lorem ispum dolor",
    avisDestinataire: "Lorem ispum dolor",
    designationMateriel: "Lorem ispum dolor",
    refComMateriel: "Lorem ispum dolor",
    dateRetour: "28/01/2022",
    avisServiceSupportAssistance: "Lorem ispum dolor",
    typeAvis:"accepter",
    newAffectation:false,
    etat:"Alerte"
  },
  {
    id: 7,
    dateFiche: "28/12/2022",
    identFiche: "Lorem ispum dolor",
    refFiche: "Ibrahima FALL",
    identMateriel: "Lorem ispum dolor",
    adresseMacMateriel: "Lorem ispum dolor",
    refInterneMateriel: "Lorem ispum dolor",
    destinataire: "Lorem ispum dolor",
    dateDotation: "28/12/2022",
    objetDotation: "Lorem ispum dolor",
    datePrevueRetour: "28/01/2022",
    localisationGeo: "Lorem ispum dolor",
    avisDestinataire: "Lorem ispum dolor",
    designationMateriel: "Lorem ispum dolor",
    refComMateriel: "Lorem ispum dolor",
    dateRetour: "28/01/2022",
    avisServiceSupportAssistance: "Lorem ispum dolor",
    typeAvis:"accepter",
    newAffectation:false,
    etat:"Alerte"
  },
]
export const MATERIELS: Materiel[] = [
  {
    id: 1,
    designationMateriel: "28/12/2022",
    typeMateriel: "Lorem ispum dolor",
    appellationCommerciale: "Lorem ispum dolor",
    marque: "Lorem ispum dolor",
    modele: "Lorem ispum dolor",
    accessoiresAssocies: "Lorem ispum dolor",
    fournisseur: "Libasse YADE",
    prixAcquisition: "28/12/2022",
    dateAcquisition: "Lorem ispum dolor",
    localisationGeo: "28/01/2022",
    numeroSerie: "Lorem ispum dolor",
    adresseMacMateriel: "Lorem ispum dolor",
    typeMaintenance: "Lorem ispum dolor",
    refInterneMateriel: "Lorem ispum dolor",
    etat:"Reformé",
    statutMateriel:"affecté"
  },
  {
    id: 2,
    designationMateriel: "28/12/2022",
    typeMateriel: "Lorem ispum dolor",
    appellationCommerciale: "Lorem ispum dolor",
    marque: "Lorem ispum dolor",
    modele: "Lorem ispum dolor",
    accessoiresAssocies: "Lorem ispum dolor",
    fournisseur: "Libasse YADE",
    prixAcquisition: "28/12/2022",
    dateAcquisition: "Lorem ispum dolor",
    localisationGeo: "28/01/2022",
    numeroSerie: "Lorem ispum dolor",
    adresseMacMateriel: "Lorem ispum dolor",
    typeMaintenance: "Lorem ispum dolor",
    refInterneMateriel: "Lorem ispum dolor",
    etat:"Actif",
    statutMateriel:"reférencié"
  },
  {
    id: 3,
    designationMateriel: "28/12/2022",
    typeMateriel: "Lorem ispum dolor",
    appellationCommerciale: "Lorem ispum dolor",
    marque: "Lorem ispum dolor",
    modele: "Lorem ispum dolor",
    accessoiresAssocies: "Lorem ispum dolor",
    fournisseur: "Libasse YADE",
    prixAcquisition: "28/12/2022",
    dateAcquisition: "Lorem ispum dolor",
    localisationGeo: "28/01/2022",
    numeroSerie: "Lorem ispum dolor",
    adresseMacMateriel: "Lorem ispum dolor",
    typeMaintenance: "Lorem ispum dolor",
    refInterneMateriel: "Lorem ispum dolor",
    etat:"Reformé",
    statutMateriel:"reférencié"
  },
  {
    id: 4,
    designationMateriel: "28/12/2022",
    typeMateriel: "Lorem ispum dolor",
    appellationCommerciale: "Lorem ispum dolor",
    marque: "Lorem ispum dolor",
    modele: "Lorem ispum dolor",
    accessoiresAssocies: "Lorem ispum dolor",
    fournisseur: "Libasse YADE",
    prixAcquisition: "28/12/2022",
    dateAcquisition: "Lorem ispum dolor",
    localisationGeo: "28/01/2022",
    numeroSerie: "Lorem ispum dolor",
    adresseMacMateriel: "Lorem ispum dolor",
    typeMaintenance: "Lorem ispum dolor",
    refInterneMateriel: "Lorem ispum dolor",
    etat:"Alerte",
    statutMateriel:"affecté"
  },
  {
    id: 5,
    designationMateriel: "28/12/2022",
    typeMateriel: "Lorem ispum dolor",
    appellationCommerciale: "Lorem ispum dolor",
    marque: "Lorem ispum dolor",
    modele: "Lorem ispum dolor",
    accessoiresAssocies: "Lorem ispum dolor",
    fournisseur: "Libasse YADE",
    prixAcquisition: "28/12/2022",
    dateAcquisition: "Lorem ispum dolor",
    localisationGeo: "28/01/2022",
    numeroSerie: "Lorem ispum dolor",
    adresseMacMateriel: "Lorem ispum dolor",
    typeMaintenance: "Lorem ispum dolor",
    refInterneMateriel: "Lorem ispum dolor",
    etat:"Alerte",
    statutMateriel:"non reférencié"
  },
  {
    id: 6,
    designationMateriel: "28/12/2022",
    typeMateriel: "Lorem ispum dolor",
    appellationCommerciale: "Lorem ispum dolor",
    marque: "Lorem ispum dolor",
    modele: "Lorem ispum dolor",
    accessoiresAssocies: "Lorem ispum dolor",
    fournisseur: "Libasse YADE",
    prixAcquisition: "28/12/2022",
    dateAcquisition: "Lorem ispum dolor",
    localisationGeo: "28/01/2022",
    numeroSerie: "Lorem ispum dolor",
    adresseMacMateriel: "Lorem ispum dolor",
    typeMaintenance: "Lorem ispum dolor",
    refInterneMateriel: "Lorem ispum dolor",
    etat:"Reformé",
    statutMateriel:"non reférencié"
  }

]

