import { ApiPaginator } from './meta-data.model';

export class ResponseApi {
  status!: string;
  payload?: any;
  message?: string;
  errors?: string;
  metadata?: ApiPaginator;
}

export enum EResponseStatut {
  OK= "OK",
  BAD_REQUEST= "BAD_REQUEST",
  UNAUTHORIZED= "UNAUTHORIZED",
  VALIDATION_EXCEPTION= "VALIDATION_EXCEPTION",
  EXCEPTION= "EXCEPTION",
  WRONG_CREDENTIALS= "WRONG_CREDENTIALS",
  ACCESS_DENIED= "ACCESS_DENIED",
  NOT_FOUND= "NOT_FOUND",
  DUPLICATE_ENTITY= "DUPLICATE_ENTITY",
  DUPLICATE_EMAIL= "DUPLICATE_EMAIL",
  DUPLICATE_REFERENCE= "DUPLICATE_REFERENCE",
  DUPLICATE_TELEPHONE= "DUPLICATE_TELEPHONE",
  DUPLICATE_NINEA= "DUPLICATE_NINEA",
  TOKEN_EXPIRED= "TOKEN_EXPIRED",
  FIRST_CONNECTION= "FIRST_CONNECTION",
  DISABLED_ACCOUNT= "DISABLED_ACCOUNT",
  INVALIDE_TOKEN= "INVALIDE_TOKEN",
  INVALIDE_URL= "INVALIDE_URL",
  UNSUPPORTED_MEDIA_TYPE= "UNSUPPORTED_MEDIA_TYPE",
  DIRECTORY_NOT_FOUND= "DIRECTORY_NOT_FOUND"
}
