spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    properties:
    #  javax:
     #   persistence:
      #    schema-generation:
       #     scripts:
        #      action: create
         #     create-target: src/main/resources/db/migration/schema/schema.sql
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect
       # ddl-auto: validate
       # ddl-auto: update
        #format-sql: true
       # show-sql: true
         #hbm2ddl:
          #delimiter: ;
        jdbc:
          time_zone: UTC

  profiles:
    active: dev
  flyway:
    enabled: false
logging:
  level:
    sn:
      gainde2000:
        #reclamationsclients: debug
        dotationclients: debug

server:
  servlet:
    encoding:
      force: true