server:
  port: 8282
  servlet:
    context-path: /dotation-api-v1
spring:
  application:
    name: dotation-api-v1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.3.80.181:5432/bdfichedotation
    username: userdot
    #password: Passer123!
    password: dev@2023
    hikari:
      max-lifetime: 9000
      minimum-idle: 0
      maximum-pool-size: 40
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false

# security
starterkit:
  app:
    jwtSecret: factoryStaterKit.comSecretKey
    jwtExpiration: 30

url:
  logo:
    starterkit: http://localhost:8282/dotation-api-v1/static/logo-artp.png
file:
  upload-dir: D:\\home\\alndiaye\\uploads\\starter-kit

app:
  url:
    front: http://localhost:4200/#/auth
    swagger: http://localhost:8282/dotation-api-v1

interval: PT30S

smtp:
  server:
    host: "172.16.2.11"
    from: "no-reply@gainde2000.sn"
