server:
  port: 8282
  servlet:
    context-path: /factory-starter-kit-api-v1
spring:
  application:
    name: factory-starter-kit-back
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/BDFactoryStaterKit
    username: postgres
    password: postgres
    hikari:
      max-lifetime: 9000
      minimum-idle: 0
      maximum-pool-size: 40
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: false
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false

# security
reclamation:
  app:
    jwtSecret: factoryStaterKit.comSecretKey
    jwtExpiration: 30

url:
  logo:
    reclamations: http://localhost:8282/factory-starter-kit-api-v1/static/logo-artp.png
file:
  upload-dir: D:\\home\\alndiaye\\uploads\\starter-kit

app:
  url:
    front: http://localhost:4200/#/auth
    swagger: http://localhost:8282/factory-starter-kit-api-v1

interval: PT30S

smtp:
  server:
    host: "172.16.2.11"
    from: "no-reply@gainde2000.sn"
